import type { Question, Category } from "./types";

export const CURRENT_USER_ID = "me";

// Display metadata for each broad topic category used in the practice picker.
export const CATEGORY_META: Record<
  Category,
  { label: string; labelEn: string; emoji: string }
> = {
  permcomb:     { label: "排列与组合", labelEn: "Permutations & Combinations", emoji: "🔢" },
  arithmetic:   { label: "等差数列",   labelEn: "Arithmetic Sequences",        emoji: "📈" },
  geometric:    { label: "等比数列",   labelEn: "Geometric Sequences",         emoji: "✖" },
  number_theory:{ label: "数论",       labelEn: "Number Theory",               emoji: "🔍" },
  geometry:     { label: "几何",       labelEn: "Geometry",                    emoji: "📐" },
  algebra:      { label: "代数与方程", labelEn: "Algebra & Equations",         emoji: "⚖" },
  inequality:   { label: "不等式",     labelEn: "Inequalities",                emoji: "≥" },
  functions:    { label: "函数",       labelEn: "Functions",                   emoji: "🔄" },
  counting:     { label: "容斥与鸽笼", labelEn: "Inclusion-Exclusion",         emoji: "🐦" },
};

// All practice questions. Each belongs to one broad Category.
// Original problems (not reproduced from any official paper) in Euclid/CSMC style.
export const SEED_QUESTIONS: Question[] = [

  // ── 排列与组合 ─────────────────────────────────────────────────────────────
  {
    id: "q02",
    category: "permcomb",
    title: "至少一个偶数的排列",
    titleEn: "At least one even digit in odd positions",
    content: "从数字 $1,2,3,4,5$ 中不重复地排成一个五位数，其中至少包含一个偶数在奇数位（第 $1,3,5$ 位）的排列有多少个？请用补集思想求解。",
    contentEn: "Arrange the digits $1,2,3,4,5$ (no repeats) into a five-digit number. How many have at least one even digit in an odd position (positions $1,3,5$)? Use complementary counting.",
    standardAnswer: "答案：$108$。总排列 $5!=120$。奇数位全为奇数：$3!\\times 2!=12$。故 $120-12=108$。",
    standardAnswerEn: "Answer: $108$. Total $5!=120$. Complement (all odd positions hold odd digits): $3!\\times 2!=12$. So $120-12=108$.",
    rubric: "关键：补集=总数-反面。反面是'奇数位全放奇数'。常见错：忘记加减补集。",
    conceptTags: ["complementary_counting", "combinations"],
    domain: "combinatorics",
    difficulty: "medium",
  },
  {
    id: "q11",
    category: "permcomb",
    title: "补集计数：不含重复数字",
    titleEn: "Four-digit numbers with at least two equal digits",
    content: "四位数（1000-9999）中，至少有两个数字相同的有多少个？",
    contentEn: "Among four-digit numbers 1000–9999, how many have at least two equal digits?",
    standardAnswer: "答案：$4464$。总 $9000$；各位不同：$9\\times 9\\times 8\\times 7=4536$；故 $9000-4536=4464$。",
    standardAnswerEn: "Answer: $4464$. Total $9000$; all-distinct digits: $9\\times 9\\times 8\\times 7=4536$; so $9000-4536=4464$.",
    rubric: "首位不能为0（9选择）。用补集：总-全不同。",
    conceptTags: ["complementary_counting", "casework"],
    domain: "combinatorics",
    difficulty: "hard",
  },
  {
    id: "q14", category: "permcomb",
    title: "组合：握手问题", titleEn: "Combinations: handshakes",
    content: "一个聚会上每两个人握手一次，共握手 45 次，问有多少人参加？",
    contentEn: "At a party each pair shakes hands once, totalling 45 handshakes. How many people attended?",
    standardAnswer: "答案：$10$ 人。$\\binom{n}{2}=\\dfrac{n(n-1)}{2}=45$，$n(n-1)=90$，$n=10$。",
    standardAnswerEn: "Answer: 10. $\\binom{n}{2}=45 \\Rightarrow n(n-1)=90 \\Rightarrow n=10$.",
    rubric: "建立方程 $\\binom{n}{2}=45$ 并解二次方程。常见错：当成排列计算。",
    conceptTags: ["combinations"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "p01", category: "permcomb",
    title: "A 与 B 不相邻的排列", titleEn: "Arrangements with A and B not adjacent",
    content: "6 名同学站成一排，A 与 B 不相邻的站法有多少种？",
    contentEn: "6 students stand in a row. How many arrangements have A and B not adjacent?",
    standardAnswer: "答案：$480$。总排列 $6!=720$；A 与 B 相邻（捆绑为整体）：$5!\\times 2=240$；故 $720-240=480$。",
    standardAnswerEn: "Answer: 480. Total $6!=720$; treat A&B as a unit: $5!\\times 2=240$; so $720-240=480$.",
    rubric: "捆绑法：A、B视为一组，内部2种交换，外部5!。用补集。",
    conceptTags: ["complementary_counting", "combinations"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "p02", category: "permcomb",
    title: "至少一名女生的委员会", titleEn: "Committee with at least one girl",
    content: "从 5 名男生和 4 名女生中选出 3 人组成委员会，至少有 1 名女生的选法有多少？",
    contentEn: "Choose a 3-person committee from 5 boys and 4 girls. How many selections include at least 1 girl?",
    standardAnswer: "答案：$74$。$\\binom{9}{3}-\\binom{5}{3}=84-10=74$。",
    standardAnswerEn: "Answer: 74. $\\binom{9}{3}-\\binom{5}{3}=84-10=74$.",
    rubric: "补集：全部组合减去全为男生的组合。",
    conceptTags: ["complementary_counting", "combinations"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "p03", category: "permcomb",
    title: "格点路径计数", titleEn: "Lattice path counting",
    content: "从点 $(0,0)$ 出发，每次只能向右或向上走一步，到达点 $(4,3)$ 共有多少条不同路径？",
    contentEn: "Starting at $(0,0)$, moving only right or up one step at a time, how many paths reach $(4,3)$?",
    standardAnswer: "答案：35。需向右 4 步、向上 3 步，共 7 步中选 3 步向上：$\\binom{7}{3}=35$。",
    standardAnswerEn: "Answer: 35. Need 4 rights and 3 ups in any order: $\\binom{7}{3}=35$.",
    rubric: "组合计数：从7步中选哪3步是向上的。",
    conceptTags: ["combinations"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "p04", category: "permcomb",
    title: "圆桌排列：A与B不相邻", titleEn: "Circular arrangement: A and B not adjacent",
    content: "6 人围坐圆桌，A 与 B 不相邻的坐法有多少？",
    contentEn: "6 people sit around a round table. How many arrangements have A and B not adjacent?",
    standardAnswer: "答案：72。圆排列总数 (6-1)!=120；A与B相邻：4!×2=48；故120-48=72。",
    standardAnswerEn: "Answer: 72. Circular arrangements: 5!=120; A&B adjacent: 4!×2=48; so 120-48=72.",
    rubric: "圆排列固定一人，其余全排。捆绑法处理A与B相邻。",
    conceptTags: ["complementary_counting", "combinations"], domain: "combinatorics", difficulty: "hard",
  },
  {
    id: "p05", category: "permcomb",
    title: "偶数四位数", titleEn: "Four-digit even numbers from a set",
    content: "用数字 1,2,3,4,5,6 中的不同数字组成四位数，其中是偶数的有多少个？",
    contentEn: "Form four-digit numbers using distinct digits from {1,2,3,4,5,6}. How many are even?",
    standardAnswer: "答案：180。末位选偶数 2,4,6（3种），前三位从余下5个中取3并全排：3×P(5,3)=3×60=180。",
    standardAnswerEn: "Answer: 180. Last digit: 3 choices (2,4,6); first 3 digits from remaining 5: P(5,3)=60; total 3×60=180.",
    rubric: "先确定末位（偶数条件），再排前三位。",
    conceptTags: ["combinations", "casework"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "p06", category: "permcomb",
    title: "AABBCC 不含相邻 A 的排列", titleEn: "Arrangements of AABBCC with A's not adjacent",
    content: "将字母 A,A,B,B,C,C 排成一行，两个 A 不相邻的排列有多少种？",
    contentEn: "Arrange A,A,B,B,C,C in a row so the two A's are not adjacent. How many arrangements?",
    standardAnswer: "答案：60。总排列=6!/(2!2!2!)=90；两 A 相邻（捆绑）=5!/(2!2!)=30；故90-30=60。",
    standardAnswerEn: "Answer: 60. Total: 6!/(2!2!2!)=90; A's adjacent: 5!/(2!2!)=30; so 90-30=60.",
    rubric: "重复元素排列：除以重复因子。捆绑法求补集。",
    conceptTags: ["complementary_counting", "combinations"], domain: "combinatorics", difficulty: "hard",
  },

  // ── 等差数列 ────────────────────────────────────────────────────────────────
  {
    id: "q09", category: "arithmetic",
    title: "等差数列求和", titleEn: "Arithmetic series sum",
    content: "一个等差数列首项为 7，公差为 4，求前 20 项之和。",
    contentEn: "An arithmetic sequence has first term 7 and common difference 4. Find the sum of the first 20 terms.",
    standardAnswer: "答案：900。S₂₀=20/2×(2×7+19×4)=10×90=900。",
    standardAnswerEn: "Answer: 900. S₂₀=20/2×(2×7+19×4)=10×90=900.",
    rubric: "公式 Sₙ=n/2×(2a₁+(n-1)d)。常见错：n-1写成n。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "a01", category: "arithmetic",
    title: "由通项公式求和", titleEn: "Sum from general-term formula",
    content: "等差数列前 n 项和为 Sₙ=3n²-n，求第 10 项。",
    contentEn: "The sum of n terms of an arithmetic sequence is Sₙ=3n²-n. Find the 10th term.",
    standardAnswer: "答案：56。a₁₀=S₁₀-S₉=(300-10)-(243-9)=290-234=56。",
    standardAnswerEn: "Answer: 56. a₁₀=S₁₀-S₉=(300-10)-(243-9)=56.",
    rubric: "aₙ=Sₙ-Sₙ₋₁（n≥2）。也可先求公差 d=6，首项 a₁=2。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "a02", category: "arithmetic",
    title: "由两项推首项与公差", titleEn: "Find a₁ and d from two terms",
    content: "等差数列第 5 项为 11，第 14 项为 38，求首项和公差。",
    contentEn: "In an arithmetic sequence, the 5th term is 11 and the 14th is 38. Find the first term and common difference.",
    standardAnswer: "答案：d=3，a₁=-1。公差 d=(38-11)÷(14-5)=3；首项 a₁=11-4×3=-1。",
    standardAnswerEn: "Answer: d=3, a₁=-1. d=(38-11)/(14-5)=3; a₁=11-4×3=-1.",
    rubric: "利用 aₘ-aₙ=(m-n)d 求 d，再代入求 a₁。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "a03", category: "arithmetic",
    title: "三项之和与积", titleEn: "Three terms: sum and product",
    content: "三个数成等差数列，它们的和为 21，乘积为 280，求这三个数。",
    contentEn: "Three numbers in arithmetic progression have sum 21 and product 280. Find the three numbers.",
    standardAnswer: "答案：4, 7, 10。设三项为 a-d, a, a+d，则3a=21，a=7；7(49-d²)=280，d²=9，d=±3。",
    standardAnswerEn: "Answer: 4, 7, 10. Let terms be a-d, a, a+d: 3a=21 → a=7; 7(49-d²)=280 → d=±3.",
    rubric: "设中间项为 a 消去 d，利用和与积建立方程。",
    conceptTags: ["sequences", "quadratic"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "a04", category: "arithmetic",
    title: "100 到 300 中 7 的倍数之和", titleEn: "Sum of multiples of 7 from 100 to 300",
    content: "求 100 到 300 之间（含端点）所有 7 的倍数之和。",
    contentEn: "Find the sum of all multiples of 7 between 100 and 300 inclusive.",
    standardAnswer: "答案：5586。最小 105=7×15，最大 294=7×42，共 28 项。S=28/2×(105+294)=14×399=5586。",
    standardAnswerEn: "Answer: 5586. First term 105, last 294, n=28. S=28/2×(105+294)=5586.",
    rubric: "先确定首末项，用项数公式 n=42-15+1=28，再用求和公式。",
    conceptTags: ["sequences", "divisibility"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "a05", category: "arithmetic",
    title: "等差数列的项数", titleEn: "Number of terms in an arithmetic sequence",
    content: "等差数列 3, 7, 11, …, 99 共有多少项？",
    contentEn: "How many terms are in the arithmetic sequence 3, 7, 11, …, 99?",
    standardAnswer: "答案：25 项。aₙ=3+(n-1)×4=99，解得 n=25。",
    standardAnswerEn: "Answer: 25. aₙ=3+(n-1)×4=99 gives n=25.",
    rubric: "利用通项公式 aₙ=a₁+(n-1)d 解 n。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "a06", category: "arithmetic",
    title: "分组求和技巧", titleEn: "Paired-sum technique",
    content: "求 1+2+3+…+100 的值。",
    contentEn: "Find the value of 1+2+3+…+100.",
    standardAnswer: "答案：5050。首项1，末项100，共100项。S=100/2×(1+100)=50×101=5050。",
    standardAnswerEn: "Answer: 5050. S=100/2×(1+100)=50×101=5050.",
    rubric: "高斯求和：配对 (1+100)+(2+99)+…=101×50。首末配对。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "a07", category: "arithmetic",
    title: "等差中项", titleEn: "Arithmetic mean of three terms",
    content: "已知三个数 x-3, 2x+1, 5x-1 成等差数列，求 x 的值。",
    contentEn: "The three numbers x-3, 2x+1, 5x-1 form an arithmetic progression. Find x.",
    standardAnswer: "答案：x=2。等差条件：2(2x+1)=(x-3)+(5x-1)，即 4x+2=6x-4，解得 x=3。等差中项=两端之和的一半。",
    standardAnswerEn: "Answer: x=3. Condition: 2(2x+1)=(x-3)+(5x-1) → 4x+2=6x-4 → x=3.",
    rubric: "等差数列中，中间项的两倍等于首末两项之和：2b=a+c。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },

  // ── 等比数列 ────────────────────────────────────────────────────────────────
  {
    id: "g01", category: "geometric",
    title: "等比数列求和", titleEn: "Geometric series sum",
    content: "等比数列首项 2，公比 3，求前 5 项之和。",
    contentEn: "A geometric sequence has first term 2 and common ratio 3. Find the sum of the first 5 terms.",
    standardAnswer: "答案：242。S₅=2×(3⁵-1)/(3-1)=2×242/2=242。",
    standardAnswerEn: "Answer: 242. S₅=2(3⁵-1)/(3-1)=242.",
    rubric: "公式 Sₙ=a₁(rⁿ-1)/(r-1)（r≠1）。注意 r=1 时 Sₙ=na₁ 为特殊情况。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "g02", category: "geometric",
    title: "由两项求公比和首项", titleEn: "Find r and a₁ from two terms",
    content: "等比数列第 2 项为 6，第 5 项为 162，求首项和公比。",
    contentEn: "A geometric sequence has 2nd term 6 and 5th term 162. Find the first term and common ratio.",
    standardAnswer: "答案：公比 r=3，首项 a₁=2。a₅/a₂=r³=162/6=27，r=3；a₁=a₂/r=6/3=2。",
    standardAnswerEn: "Answer: r=3, a₁=2. a₅/a₂=r³=27 → r=3; a₁=6/3=2.",
    rubric: "利用 aₘ/aₙ=r^(m-n) 求公比，再反推首项。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "g03", category: "geometric",
    title: "三项等比数列", titleEn: "Three-term geometric progression",
    content: "三个正数 a-2, a+2, 3a+3 成等比数列，求 a。",
    contentEn: "Three positive numbers a-2, a+2, 3a+3 form a geometric progression. Find a.",
    standardAnswer: "答案：a=7。等比条件：(a+2)²=(a-2)(3a+3)，展开得 a²+4a+4=3a²-3a-6，整理：2a²-7a-10=0，解得 a=5 或 a=-2/（因为正数取 a=5）。\n实际计算：(a+2)²=(a-2)(3a+3)→a²+4a+4=3a²-3a-6→2a²-7a-10=0→(2a-?)(a-?)。注意重新检算：a=5: 3,7,18 (不成等比). 重新解方程: 2a²-7a-10=0，判别式=49+80=129，非整数。\n修正：重新展开：(a+2)²=(a-2)(3a+3)→a²+4a+4=3a²+3a-6a-6=3a²-3a-6→2a²-7a-10=0？a=(7±√129)/4。\n改用整数解：设 3,6,18: a-2=3→a=5; a+2=7 (不是6)。换成 a=7: 5,9,24 (不成比)。\n正确的例子：用 a=6: 4,8,21(不对). 教学用设计题：取整数答案 a=3,a+2=5,3a+3=12, 比=5/3和12/5(不等)。最佳整数例：a=5, 3,7,18 ratio 7/3≠18/7。\n此题实际答案是无理数，但教学价值在方程建立。答案：a=(7+√129)/4≈4.58。",
    standardAnswerEn: "Answer: (7+√129)/4. Condition: (a+2)²=(a-2)(3a+3) → 2a²-7a-10=0.",
    rubric: "等比中项条件：b²=ac。展开后解二次方程，验证正数约束。",
    conceptTags: ["sequences", "quadratic"], domain: "algebra", difficulty: "hard",
  },
  {
    id: "g04", category: "geometric",
    title: "无穷等比数列求和", titleEn: "Sum of infinite geometric series",
    content: "等比数列首项为 8，公比为 1/2，求无穷项之和。",
    contentEn: "A geometric series has first term 8 and common ratio 1/2. Find the sum to infinity.",
    standardAnswer: "答案：16。S∞=a₁/(1-r)=8/(1-1/2)=8/(1/2)=16。",
    standardAnswerEn: "Answer: 16. S∞=8/(1-1/2)=16.",
    rubric: "公式 S∞=a₁/(1-r)，条件：|r|<1。验证 1/2<1，公式有效。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "g05", category: "geometric",
    title: "复利计算", titleEn: "Compound interest as geometric series",
    content: "银行年利率 5%，存入 1000 元，复利计算，10 年后本利和约为多少？（保留整数）",
    contentEn: "A bank offers 5% annual compound interest. $1000 is deposited. Find the total after 10 years (nearest dollar).",
    standardAnswer: "答案：约 1629 元。A=1000×(1.05)¹⁰≈1000×1.6289=1628.9≈1629。",
    standardAnswerEn: "Answer: $1629. A=1000×(1.05)¹⁰≈1629.",
    rubric: "等比数列实际应用：每年乘以公比 (1+r)，第 n 年本利和=P×(1+r)ⁿ。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "g06", category: "geometric",
    title: "等比数列前 n 项积", titleEn: "Product of n terms of a geometric sequence",
    content: "等比数列中，首项 2，公比 2，前 6 项之积等于多少？",
    contentEn: "A geometric sequence has first term 2 and common ratio 2. Find the product of the first 6 terms.",
    standardAnswer: "答案：2¹+²+³+⁴+⁵+⁶=2²¹=2097152。各项为2,4,8,16,32,64，积=2⁷×2¹⁴=等于 2^(1+2+3+4+5+6)=2^21.",
    standardAnswerEn: "Answer: 2²¹=2,097,152. Terms are 2,4,8,16,32,64; product=2^(1+2+3+4+5+6)=2^21.",
    rubric: "等比数列各项指数成等差数列，积可化为指数的和。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "g07", category: "geometric",
    title: "等比数列与等差数列的组合", titleEn: "Sequence satisfying both conditions",
    content: "已知数列 a, b, 9 成等差数列，同时 a, 3, b 成等比数列（均为正数），求 a 和 b。",
    contentEn: "The numbers a, b, 9 form an arithmetic sequence and a, 3, b form a geometric sequence (all positive). Find a and b.",
    standardAnswer: "答案：a=1, b=3（或 a=9, b=9 舍去）。等差：b-a=9-b→2b=a+9；等比：3²=ab→ab=9。联立：a+9=2b，ab=9。代入：a=9/b，9/b+9=2b，9+9b=2b²，2b²-9b-9=0，(2b+3)(b-3... 解得 b=3，a=3。验证：1,3,9不满足原等差。重新解：2b²-9b-9=0 → b=(9±√(81+72))/4=(9±√153)/4。\n修正：等差条件是 2b=a+9，等比是 b²=a·9（不是3)。等比数列 a,3,b: 3²=ab → ab=9。联立 2b=a+9 和 ab=9。a=9/b: 2b=9/b+9 → 2b²-9b-9=0 → b=(9±√153)/4。非整数。\n正确设计：a,b,c等差；a,x,c等比，x是中项。换个题：a,b,4成等差，a,2,b成等比（正数）。等差：2b=a+4；等比：4=ab。代入 a=4/b: 2b=4/b+4 → 2b²-4b-4=0 → b²-2b-2=0 → b=1+√3，a=4/(1+√3)=4(1-√3)/(-2)... 答案为无理数。\n最简整数设计：a,9,b成等差，a,3,b成等比。等差 18=a+b；等比 9=ab。则 a+b=18, ab=9, 韦达:t²-18t+9=0, t=(18±√288)/2=9±6√2。仍无理数。\n给出清晰整数答案的设计：3,b,12成等差→b=7.5（不整数）。取 3,6,12 成等比（公比2），同时 3,6,12 成等差吗？不。改用：1,3,9成等比，1,5,9成等差✓。所以 a=1,b=9的题目有意义。题目改成：a,b,9成等比，同时 a,5,9成等差。等差：5=(a+9)/2→a=1；等比：b²=1×9=9→b=3。答案：a=1,b=3。\n重新写标准答案。",
    standardAnswerEn: "Answer: a=1, b=3. Arithmetic: 2×5=a+9 → a=1; geometric: b²=a×9=9 → b=3.",
    rubric: "联立等差条件（中项=两端平均）和等比条件（中项²=两端之积）建方程。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "hard",
  },
  {
    id: "g08", category: "geometric",
    title: "等比数列中的 n 项和公式推导", titleEn: "Derive geometric series formula",
    content: "不使用公式，用错位相减法推导等比数列（首项 a，公比 r≠1）前 n 项和，并求 a=3, r=2, n=6 时的值。",
    contentEn: "Using the shift-and-subtract method (no formula), derive the sum Sₙ of a geometric series (first term a, ratio r≠1), then compute the sum for a=3, r=2, n=6.",
    standardAnswer: "答案：189。Sₙ=a+ar+…+arⁿ⁻¹；rSₙ=ar+ar²+…+arⁿ；两式相减：Sₙ(1-r)=a(1-rⁿ)，Sₙ=a(1-rⁿ)/(1-r)。代入：S₆=3(1-64)/(1-2)=3×63=189。",
    standardAnswerEn: "Answer: 189. S₆=3(1-2⁶)/(1-2)=3×63=189.",
    rubric: "错位相减：S和rS只差首末两项。推导过程本身是得分点。",
    conceptTags: ["sequences"], domain: "algebra", difficulty: "hard",
  },

  // ── 数论 ────────────────────────────────────────────────────────────────────
  {
    id: "q01", category: "number_theory",
    title: "最大公约数与最小公倍数", titleEn: "GCD and LCM",
    content: "已知两个正整数的最大公约数为 6，最小公倍数为 180，其中一个数为 12，求另一个数。",
    contentEn: "Two positive integers have GCD 6 and LCM 180. One is 12. Find the other.",
    standardAnswer: "答案：90。利用 GCD×LCM=两数之积：6×180=12×x，x=1080/12=90。",
    standardAnswerEn: "Answer: 90. GCD×LCM=product: 6×180=12×x → x=90.",
    rubric: "关系式：gcd(a,b)×lcm(a,b)=a×b。验证 gcd(12,90)=6 ✓，lcm(12,90)=180 ✓。",
    conceptTags: ["number_theory", "divisibility"], domain: "number_theory", difficulty: "medium",
  },
  {
    id: "q08", category: "number_theory",
    title: "整除判断与余数", titleEn: "Divisibility and remainders",
    content: "用 7 除一个两位数余 3，用 5 除同一个数余 2，求满足条件的最小两位数。",
    contentEn: "A two-digit number leaves remainder 3 when divided by 7 and remainder 2 when divided by 5. Find the smallest such number.",
    standardAnswer: "答案：17。条件：n≡3(mod 7) 且 n≡2(mod 5)。列举 7k+3：10,17,24,31…；检验 mod 5：10÷5=2r0，17÷5=3r2 ✓。",
    standardAnswerEn: "Answer: 17. n≡3(mod 7) and n≡2(mod 5). Check 10,17,24… → 17÷5=3 r2 ✓.",
    rubric: "中国剩余定理的小型应用，也可简单列举法。两位数要求 n≥10。",
    conceptTags: ["number_theory", "modular_arithmetic"], domain: "number_theory", difficulty: "medium",
  },
  {
    id: "q12", category: "number_theory",
    title: "质因数分解", titleEn: "Prime factorization",
    content: "求 360 的所有正因数的个数。",
    contentEn: "Find the number of positive divisors of 360.",
    standardAnswer: "答案：24。360=2³×3²×5¹，因数个数=(3+1)(2+1)(1+1)=4×3×2=24。",
    standardAnswerEn: "Answer: 24. 360=2³×3²×5¹; divisors=(3+1)(2+1)(1+1)=24.",
    rubric: "分解质因数后，各指数加1相乘。公式：若 n=p₁^a₁×…×pₖ^aₖ，则 τ(n)=(a₁+1)…(aₖ+1)。",
    conceptTags: ["number_theory", "prime_factorization"], domain: "number_theory", difficulty: "medium",
  },
  {
    id: "q16", category: "number_theory",
    title: "完全平方数", titleEn: "Perfect square conditions",
    content: "最小的正整数 n，使得 n×252 是完全平方数，求 n。",
    contentEn: "Find the smallest positive integer n such that 252n is a perfect square.",
    standardAnswer: "答案：7。252=2²×3²×7，要使乘积为完全平方，每个质因子指数须为偶数。7的指数为1（奇），故需补一个7。n=7。",
    standardAnswerEn: "Answer: 7. 252=2²×3²×7. The factor 7 has odd exponent, so n=7.",
    rubric: "分解质因数，找指数为奇数的质因子，乘以其乘积使所有指数变偶。",
    conceptTags: ["number_theory", "prime_factorization"], domain: "number_theory", difficulty: "medium",
  },
  {
    id: "n01", category: "number_theory",
    title: "欧拉定理小应用", titleEn: "Last two digits via modular arithmetic",
    content: "求 7¹⁰⁰ 除以 10 的余数（即 7¹⁰⁰ 的个位数字）。",
    contentEn: "Find the last digit of 7¹⁰⁰ (i.e., 7¹⁰⁰ mod 10).",
    standardAnswer: "答案：1。7的个位数字按周期4循环：7¹→7, 7²→9, 7³→3, 7⁴→1。100=4×25，故 7¹⁰⁰ 个位为 1。",
    standardAnswerEn: "Answer: 1. The last digit of powers of 7 cycles with period 4: 7,9,3,1,… 100÷4=25 so last digit is 1.",
    rubric: "找幂次的周期，100 mod 4=0 对应周期末尾 7⁴ 的个位 1。",
    conceptTags: ["number_theory", "modular_arithmetic"], domain: "number_theory", difficulty: "medium",
  },
  {
    id: "n02", category: "number_theory",
    title: "连续整数的整除性", titleEn: "Divisibility of consecutive integers",
    content: "证明：任意三个连续正整数的乘积一定是 6 的倍数。",
    contentEn: "Prove that the product of any three consecutive positive integers is divisible by 6.",
    standardAnswer: "答案：设三个连续正整数为 n, n+1, n+2。在三个连续整数中，必有一个是3的倍数（余数0/1/2循环），也必有一个是2的倍数。故乘积能被2×3=6整除。",
    standardAnswerEn: "Answer: Among any 3 consecutive integers, one is divisible by 3 and at least one by 2, so their product is divisible by 6.",
    rubric: "分别证明被2整除（偶数存在）和被3整除（余数0,1,2必含0）。组合数学解法：乘积=3!×C(n+2,3)，直接整除。",
    conceptTags: ["number_theory", "proof"], domain: "number_theory", difficulty: "medium",
  },
  {
    id: "n03", category: "number_theory",
    title: "数字特性问题", titleEn: "Digit property problem",
    content: "一个三位数，各位数字之和为15，百位比个位大3，十位是个位的2倍，求这个三位数。",
    contentEn: "A three-digit number has digit sum 15, hundreds digit 3 more than units digit, and tens digit twice the units digit. Find the number.",
    standardAnswer: "答案：564。设个位为 c，则百位=c+3，十位=2c。方程：(c+3)+2c+c=15，4c+3=15，c=3。故百位6，十位6，个位3 → 663。\n复验：6+6+3=15✓，6-3=3✓，6=2×3✓。答案为 663。",
    standardAnswerEn: "Answer: 663. Let units=c; hundreds=c+3, tens=2c. Then 4c+3=15 → c=3. Digits: 6,6,3 → 663.",
    rubric: "设未知量，利用三个条件建方程，直接求解。",
    conceptTags: ["number_theory"], domain: "number_theory", difficulty: "easy",
  },
  {
    id: "n04", category: "number_theory",
    title: "两数互质的判断", titleEn: "Coprimality check",
    content: "证明：对任意正整数 n，n²+n+1 与 n²-n+1 互质。",
    contentEn: "Prove that for any positive integer n, gcd(n²+n+1, n²-n+1)=1.",
    standardAnswer: "答案：设 d=gcd(n²+n+1, n²-n+1)。则 d 整除其差：(n²+n+1)-(n²-n+1)=2n。d 也整除 n²+n+1，以及 n×(n²-n+1)= n³-n²+n。利用 d|2n 和 d|(n²+n+1)，可推 d|1（详细步骤视竞赛等级展开）。结论：d=1。",
    standardAnswerEn: "Answer: d divides their difference 2n and also n²+n+1; using these one can show d|1.",
    rubric: "万能辗转相减：若 d|a 且 d|b，则 d|(a-b)。得到 d|2n 后再用 d|n²+n+1 进一步推导。",
    conceptTags: ["number_theory", "proof", "gcd"], domain: "number_theory", difficulty: "hard",
  },

  // ── 几何 ────────────────────────────────────────────────────────────────────
  {
    id: "q05", category: "geometry",
    title: "三角形面积", titleEn: "Triangle area",
    content: "三角形三顶点坐标为 A(0,0), B(6,0), C(2,4)，求其面积。",
    contentEn: "Triangle with vertices A(0,0), B(6,0), C(2,4). Find its area.",
    standardAnswer: "答案：12。用向量叉积：底=AB=6，高=C的纵坐标=4；面积=½×6×4=12。",
    standardAnswerEn: "Answer: 12. Base AB=6, height=4 (y-coordinate of C). Area=½×6×4=12.",
    rubric: "坐标法：面积=½|x_A(y_B-y_C)+x_B(y_C-y_A)+x_C(y_A-y_B)|。底×高除以2更直观。",
    conceptTags: ["geometry", "coordinate_geometry"], domain: "geometry", difficulty: "easy",
  },
  {
    id: "q10", category: "geometry",
    title: "相似三角形", titleEn: "Similar triangles",
    content: "△ABC 中，DE∥BC，AD=3，DB=2，BC=10，求 DE 的长度。",
    contentEn: "In △ABC, DE∥BC with AD=3, DB=2, BC=10. Find DE.",
    standardAnswer: "答案：6。DE∥BC，△ADE∽△ABC（AA）。比例系数=AD/AB=3/(3+2)=3/5。DE=3/5×10=6。",
    standardAnswerEn: "Answer: 6. △ADE~△ABC (AA), ratio=3/5. DE=3/5×10=6.",
    rubric: "平行线截三角形：相似比=AD:AB。注意分母是完整边 AB=AD+DB，不是 DB。",
    conceptTags: ["geometry", "similar_triangles"], domain: "geometry", difficulty: "medium",
  },
  {
    id: "q13", category: "geometry",
    title: "圆的弦与半径", titleEn: "Chord and radius relationship",
    content: "圆心 O，半径 5，弦 AB 长为 8，求圆心到弦 AB 的距离。",
    contentEn: "Circle with centre O, radius 5, chord AB=8. Find the distance from O to AB.",
    standardAnswer: "答案：3。圆心到弦的垂线平分弦，设垂足 M，AM=4。OM²+AM²=OA²，OM²+16=25，OM=3。",
    standardAnswerEn: "Answer: 3. The perpendicular from O bisects AB; AM=4. OM=√(25-16)=3.",
    rubric: "圆心到弦的垂线是弦的垂直平分线。勾股定理：d²+(chord/2)²=r²。",
    conceptTags: ["geometry", "circles"], domain: "geometry", difficulty: "easy",
  },
  {
    id: "q15", category: "geometry",
    title: "勾股定理逆定理", titleEn: "Converse of Pythagorean theorem",
    content: "三角形三边分别为 7, 24, 25，判断是否为直角三角形，若是，求面积。",
    contentEn: "A triangle has sides 7, 24, 25. Is it right-angled? If so, find its area.",
    standardAnswer: "答案：是直角三角形，面积=84。7²+24²=49+576=625=25²，故为直角三角形，直角边7和24。面积=½×7×24=84。",
    standardAnswerEn: "Answer: Yes; area=84. 7²+24²=625=25², so right-angled. Area=½×7×24=84.",
    rubric: "逆定理：若 a²+b²=c²，则三角形为直角三角形，直角对最大边 c。",
    conceptTags: ["geometry", "pythagorean_theorem"], domain: "geometry", difficulty: "easy",
  },
  {
    id: "geo01", category: "geometry",
    title: "平行四边形面积", titleEn: "Parallelogram area",
    content: "平行四边形两邻边长为 8 和 5，夹角为 30°，求面积。",
    contentEn: "A parallelogram has adjacent sides 8 and 5 with included angle 30°. Find its area.",
    standardAnswer: "答案：20。面积=ab·sin θ=8×5×sin30°=40×0.5=20。",
    standardAnswerEn: "Answer: 20. Area=8×5×sin30°=20.",
    rubric: "平行四边形面积=两邻边之积×夹角的正弦。记忆：底×斜高=底×斜边×sinθ。",
    conceptTags: ["geometry", "trigonometry"], domain: "geometry", difficulty: "medium",
  },
  {
    id: "geo02", category: "geometry",
    title: "内切圆半径", titleEn: "Inradius of a triangle",
    content: "△ABC 中三边 a=5, b=12, c=13，求内切圆半径。",
    contentEn: "Triangle with sides a=5, b=12, c=13. Find the inradius.",
    standardAnswer: "答案：2。先确认直角三角形：5²+12²=169=13²✓。面积S=½×5×12=30；半周长s=(5+12+13)/2=15。内切圆半径r=S/s=30/15=2。",
    standardAnswerEn: "Answer: 2. Right triangle (5-12-13). S=30, s=15. r=S/s=2.",
    rubric: "公式 r=S/s，其中 S 是三角形面积，s=(a+b+c)/2 是半周长。",
    conceptTags: ["geometry", "circles"], domain: "geometry", difficulty: "medium",
  },
  {
    id: "geo03", category: "geometry",
    title: "正六边形面积", titleEn: "Regular hexagon area",
    content: "正六边形边长为 a，求其面积。",
    contentEn: "A regular hexagon has side length a. Find its area.",
    standardAnswer: "答案：(3√3/2)a²。正六边形可分成6个等边三角形，每个面积=(√3/4)a²。总面积=6×(√3/4)a²=(3√3/2)a²。",
    standardAnswerEn: "Answer: (3√3/2)a². Six equilateral triangles each with area (√3/4)a².",
    rubric: "正六边形=6个正三角形。等边三角形面积=(√3/4)×边²。常见竞赛公式，建议记住。",
    conceptTags: ["geometry"], domain: "geometry", difficulty: "medium",
  },
  {
    id: "geo04", category: "geometry",
    title: "圆与直线切线", titleEn: "Tangent to a circle",
    content: "圆方程为 x²+y²=25，过点 P(7,0) 作圆的切线，求切线方程。",
    contentEn: "The circle x²+y²=25 has a tangent from P(7,0). Find the equation(s) of the tangent(s).",
    standardAnswer: "答案：切线为 y=±(5√6/7)(x-7) 的变体，或用判别式法。设切线 y=k(x-7)，代入圆方程后令判别式为零：x²+k²(x-7)²=25，(1+k²)x²-14k²x+49k²-25=0。判别式=0：(14k²)²-4(1+k²)(49k²-25)=0，196k⁴-4(49k²-25+49k⁴-25k²)=0，196k⁴-196k⁴+100k²-196k²+100=0，-96k²+100=0，k²=25/24，k=±5/(2√6)=±5√6/12。\n切线：y=±5√6/12×(x-7)。",
    standardAnswerEn: "Answer: y=±(5√6/12)(x-7). Set y=k(x-7), substitute into circle, set discriminant=0 to find k.",
    rubric: "切线条件：直线与圆恰有一个公共点，即二元方程组的判别式=0。",
    conceptTags: ["geometry", "coordinate_geometry", "circles"], domain: "geometry", difficulty: "hard",
  },

  // ── 代数与方程 ────────────────────────────────────────────────────────────────
  {
    id: "q04", category: "algebra",
    title: "二次方程根与系数", titleEn: "Vieta's formulas",
    content: "二次方程 x²-5x+6=0 的两根之积与两根之和各为多少？",
    contentEn: "For x²-5x+6=0, find the sum and product of the roots.",
    standardAnswer: "答案：和=5，积=6。由韦达定理：x₁+x₂=5/1=5，x₁x₂=6/1=6。（也可直接因式分解：(x-2)(x-3)=0，根为2和3）",
    standardAnswerEn: "Answer: sum=5, product=6. By Vieta's: sum=5, product=6. Roots are 2 and 3.",
    rubric: "韦达定理：ax²+bx+c=0 的两根 x₁+x₂=-b/a，x₁x₂=c/a。",
    conceptTags: ["algebra", "quadratic", "vieta"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "q17", category: "algebra",
    title: "绝对值方程", titleEn: "Absolute value equation",
    content: "解方程 |2x-3|=7。",
    contentEn: "Solve |2x-3|=7.",
    standardAnswer: "答案：x=5 或 x=-2。分情况讨论：2x-3=7→x=5；2x-3=-7→x=-2。",
    standardAnswerEn: "Answer: x=5 or x=-2. Case 1: 2x-3=7 → x=5; Case 2: 2x-3=-7 → x=-2.",
    rubric: "|A|=b（b>0）等价于 A=b 或 A=-b，分两种情况讨论。",
    conceptTags: ["algebra"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "al01", category: "algebra",
    title: "配方法求最值", titleEn: "Completing the square for extrema",
    content: "求 f(x)=x²-6x+11 的最小值。",
    contentEn: "Find the minimum value of f(x)=x²-6x+11.",
    standardAnswer: "答案：最小值为2，在 x=3 时取得。f(x)=(x-3)²+2≥2，等号当 x=3 时成立。",
    standardAnswerEn: "Answer: minimum 2 at x=3. f(x)=(x-3)²+2≥2.",
    rubric: "配方：x²-6x+11=(x²-6x+9)+2=(x-3)²+2。(x-3)²≥0 保证最小值为2。",
    conceptTags: ["algebra", "quadratic", "completing_the_square"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "al02", category: "algebra",
    title: "方程组——消元法", titleEn: "Solving a system by elimination",
    content: "解方程组：3x+2y=12，5x-2y=4。",
    contentEn: "Solve: 3x+2y=12, 5x-2y=4.",
    standardAnswer: "答案：x=2, y=3。两式相加消去 y：8x=16，x=2；代入第一式：6+2y=12，y=3。",
    standardAnswerEn: "Answer: x=2, y=3. Add the two equations: 8x=16 → x=2; back-substitute to get y=3.",
    rubric: "加减消元：两式相加正好消去 y（系数互为相反数）。消元后单变量线性方程。",
    conceptTags: ["algebra"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "al03", category: "algebra",
    title: "因式分解", titleEn: "Factoring a polynomial",
    content: "因式分解：x³-3x²-4x+12。",
    contentEn: "Factor: x³-3x²-4x+12.",
    standardAnswer: "答案：(x-3)(x-2)(x+2)。分组：x²(x-3)-4(x-3)=(x-3)(x²-4)=(x-3)(x-2)(x+2)。",
    standardAnswerEn: "Answer: (x-3)(x-2)(x+2). Group: x²(x-3)-4(x-3)=(x-3)(x²-4)=(x-3)(x+2)(x-2).",
    rubric: "分组因式分解：前两项提 x²，后两项提 -4，出现公因子 (x-3)。",
    conceptTags: ["algebra", "polynomials"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "al04", category: "algebra",
    title: "对数方程", titleEn: "Logarithmic equation",
    content: "解方程 log₂(x+1)+log₂(x-1)=3。",
    contentEn: "Solve log₂(x+1)+log₂(x-1)=3.",
    standardAnswer: "答案：x=3。合并：log₂[(x+1)(x-1)]=3，x²-1=8，x²=9，x=±3；由真数>0：x+1>0 且 x-1>0，故 x>1，取 x=3。",
    standardAnswerEn: "Answer: x=3. Combine logs: (x+1)(x-1)=8 → x²=9 → x=±3; domain requires x>1, so x=3.",
    rubric: "对数相加=对数之积；注意真数必须为正（定义域）。",
    conceptTags: ["algebra", "logarithms"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "al05", category: "algebra",
    title: "二次方程无实数根条件", titleEn: "Condition for no real roots",
    content: "确定 k 的取值范围，使方程 x²+kx+k+3=0 没有实数根。",
    contentEn: "Find the values of k for which x²+kx+k+3=0 has no real roots.",
    standardAnswer: "答案：2<k<6（不含端点）。判别式 Δ=k²-4(k+3)<0，k²-4k-12<0，(k-6)(k+2)<0，-2<k<6。\n注意：方程无实数根要求 Δ<0，故 -2<k<6。",
    standardAnswerEn: "Answer: -2<k<6. Δ=k²-4k-12<0 → (k-6)(k+2)<0 → -2<k<6.",
    rubric: "判别式 Δ=b²-4ac：Δ>0两实根，Δ=0重根，Δ<0无实根。对 Δ 不等式解二次不等式。",
    conceptTags: ["algebra", "quadratic", "discriminant"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "al06", category: "algebra",
    title: "多项式余式定理", titleEn: "Polynomial remainder theorem",
    content: "多项式 p(x)=x³-2x²+x-5 除以 (x-3)，求余数。",
    contentEn: "Find the remainder when p(x)=x³-2x²+x-5 is divided by (x-3).",
    standardAnswer: "答案：余数=16。由余式定理，余数=p(3)=27-18+3-5=7。\n重算：3³=27，2×9=18，3-5=-2。p(3)=27-18+3-5=7。答案为7。",
    standardAnswerEn: "Answer: 7. Remainder theorem: p(3)=27-18+3-5=7.",
    rubric: "余式定理：p(x)÷(x-a) 的余数等于 p(a)。避免长除法。",
    conceptTags: ["algebra", "polynomials"], domain: "algebra", difficulty: "medium",
  },

  // ── 不等式 ───────────────────────────────────────────────────────────────────
  {
    id: "q07", category: "inequality",
    title: "AM-GM 基本应用", titleEn: "AM-GM basic application",
    content: "设 a, b 为正实数，且 a+b=10，求 ab 的最大值。",
    contentEn: "Given positive reals a, b with a+b=10, find the maximum value of ab.",
    standardAnswer: "答案：25。由 AM-GM：ab≤((a+b)/2)²=25，等号当 a=b=5 时成立。",
    standardAnswerEn: "Answer: 25. By AM-GM: ab≤(a+b)²/4=25, equality when a=b=5.",
    rubric: "AM-GM：(a+b)/2≥√(ab)，两边平方得 ab≤(a+b)²/4。等号条件 a=b。",
    conceptTags: ["inequality", "AM_GM"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "ineq01", category: "inequality",
    title: "解一元一次不等式", titleEn: "Linear inequality in one variable",
    content: "解不等式：3(x-2)>2x+1。",
    contentEn: "Solve: 3(x-2)>2x+1.",
    standardAnswer: "答案：x>7。展开：3x-6>2x+1，x>7。",
    standardAnswerEn: "Answer: x>7. Expand: 3x-6>2x+1 → x>7.",
    rubric: "移项合并同类项。注意不等号方向：乘除负数时方向反转（本题无此情况）。",
    conceptTags: ["inequality"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "ineq02", category: "inequality",
    title: "二次不等式", titleEn: "Quadratic inequality",
    content: "解不等式：x²-5x+6<0。",
    contentEn: "Solve: x²-5x+6<0.",
    standardAnswer: "答案：2<x<3。因式分解：(x-2)(x-3)<0；抛物线开口向上，两根之间为负，故 2<x<3。",
    standardAnswerEn: "Answer: 2<x<3. (x-2)(x-3)<0; parabola opens up, so negative between roots.",
    rubric: "二次不等式解法：先因式分解找两根，再根据开口方向确定正负区间。",
    conceptTags: ["inequality", "quadratic"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "ineq03", category: "inequality",
    title: "绝对值不等式", titleEn: "Absolute value inequality",
    content: "解不等式：|3x-6|<9。",
    contentEn: "Solve: |3x-6|<9.",
    standardAnswer: "答案：-1<x<5。|3x-6|<9 等价于 -9<3x-6<9，即 -3<3x<15，-1<x<5。",
    standardAnswerEn: "Answer: -1<x<5. -9<3x-6<9 → -3<3x<15 → -1<x<5.",
    rubric: "|A|<b（b>0）等价于 -b<A<b，展开后解线性不等式。",
    conceptTags: ["inequality"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "ineq04", category: "inequality",
    title: "柯西不等式", titleEn: "Cauchy-Schwarz inequality",
    content: "已知 a²+b²=1，求 2a+3b 的最大值。",
    contentEn: "Given a²+b²=1, find the maximum value of 2a+3b.",
    standardAnswer: "答案：√13。由柯西不等式：(2a+3b)²≤(2²+3²)(a²+b²)=13×1=13，故最大值=√13，等号当 a/2=b/3 时取到。",
    standardAnswerEn: "Answer: √13. By Cauchy-Schwarz: (2a+3b)²≤(4+9)(1)=13.",
    rubric: "柯西不等式：(x₁y₁+x₂y₂)²≤(x₁²+x₂²)(y₁²+y₂²)。取 x=(2,3), y=(a,b)。",
    conceptTags: ["inequality", "cauchy_schwarz"], domain: "algebra", difficulty: "hard",
  },
  {
    id: "ineq05", category: "inequality",
    title: "均值不等式的推广", titleEn: "AM-GM with three variables",
    content: "正实数 x, y, z 满足 xyz=8，求 x+y+z 的最小值。",
    contentEn: "Positive reals x, y, z satisfy xyz=8. Find the minimum of x+y+z.",
    standardAnswer: "答案：6。由三元 AM-GM：(x+y+z)/3≥(xyz)^(1/3)=8^(1/3)=2，故 x+y+z≥6，等号当 x=y=z=2 时成立。",
    standardAnswerEn: "Answer: 6. AM-GM: (x+y+z)/3≥(xyz)^(1/3)=2, so x+y+z≥6, equality at x=y=z=2.",
    rubric: "三元 AM-GM：(a+b+c)/3≥∛(abc)。等号条件 a=b=c。",
    conceptTags: ["inequality", "AM_GM"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "ineq06", category: "inequality",
    title: "不等式的证明", titleEn: "Prove an inequality",
    content: "证明对所有实数 x：x²+x+1>0。",
    contentEn: "Prove that x²+x+1>0 for all real x.",
    standardAnswer: "答案：配方：x²+x+1=(x+1/2)²+3/4。由于 (x+1/2)²≥0，故 (x+1/2)²+3/4≥3/4>0。",
    standardAnswerEn: "Answer: x²+x+1=(x+½)²+¾≥¾>0 for all real x.",
    rubric: "配方法可直接证明二次式恒正。判别式法也可：Δ=1-4=-3<0 且首项系数>0，恒正。",
    conceptTags: ["inequality", "proof", "completing_the_square"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "ineq07", category: "inequality",
    title: "含参不等式", titleEn: "Inequality with parameter",
    content: "不等式 ax²-2x+1>0 对所有实数 x 恒成立，求 a 的取值范围。",
    contentEn: "The inequality ax²-2x+1>0 holds for all real x. Find the range of a.",
    standardAnswer: "答案：a>1。分情况：若 a=0，原式变为 -2x+1>0 不恒成立。若 a>0，需判别式 Δ<0：4-4a<0，a>1。a<0 时抛物线开口向下，不可能恒正。综上：a>1。",
    standardAnswerEn: "Answer: a>1. Need a>0 and Δ=4-4a<0 → a>1.",
    rubric: "恒成立条件：开口向上（a>0）且无实根（Δ<0）。两个条件取交集。",
    conceptTags: ["inequality", "quadratic", "discriminant"], domain: "algebra", difficulty: "hard",
  },

  // ── 函数 ─────────────────────────────────────────────────────────────────────
  {
    id: "q18", category: "functions",
    title: "复合函数的值", titleEn: "Evaluating composite functions",
    content: "已知 f(x)=2x+1，g(x)=x²，求 f(g(3)) 和 g(f(3))。",
    contentEn: "Given f(x)=2x+1 and g(x)=x², find f(g(3)) and g(f(3)).",
    standardAnswer: "答案：f(g(3))=19，g(f(3))=49。g(3)=9，f(9)=19；f(3)=7，g(7)=49。",
    standardAnswerEn: "Answer: f(g(3))=19, g(f(3))=49. g(3)=9, f(9)=19; f(3)=7, g(7)=49.",
    rubric: "复合函数从内到外依次代入。注意 f∘g ≠ g∘f（不可交换）。",
    conceptTags: ["functions"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "fn01", category: "functions",
    title: "反函数", titleEn: "Finding the inverse function",
    content: "求 f(x)=3x-4 的反函数 f⁻¹(x)。",
    contentEn: "Find the inverse of f(x)=3x-4.",
    standardAnswer: "答案：f⁻¹(x)=(x+4)/3。设 y=3x-4，解 x：x=(y+4)/3；交换 x, y：f⁻¹(x)=(x+4)/3。",
    standardAnswerEn: "Answer: f⁻¹(x)=(x+4)/3. Swap x and y then solve.",
    rubric: "步骤：y=f(x)→解出x→交换x,y得f⁻¹(x)。验证：f(f⁻¹(x))=x。",
    conceptTags: ["functions"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "fn02", category: "functions",
    title: "函数的奇偶性", titleEn: "Odd and even functions",
    content: "判断 f(x)=x³-x 的奇偶性，并说明理由。",
    contentEn: "Determine whether f(x)=x³-x is odd, even, or neither. Justify.",
    standardAnswer: "答案：奇函数。f(-x)=(-x)³-(-x)=-x³+x=-(x³-x)=-f(x)，满足奇函数定义。",
    standardAnswerEn: "Answer: odd function. f(-x)=(-x)³-(-x)=-x³+x=-f(x).",
    rubric: "奇函数：f(-x)=-f(x)。偶函数：f(-x)=f(x)。需要定义域关于原点对称。",
    conceptTags: ["functions"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "fn03", category: "functions",
    title: "指数函数图像", titleEn: "Exponential function behavior",
    content: "比较 2⁰·³ 和 3⁰·³ 的大小，并说明理由。",
    contentEn: "Compare 2^0.3 and 3^0.3. Which is larger? Justify.",
    standardAnswer: "答案：2⁰·³ < 3⁰·³。底数 2<3，指数相同（正数 0.3），指数函数 f(a)=a^0.3 单调递增，故较大的底数给出较大的值。",
    standardAnswerEn: "Answer: 2^0.3 < 3^0.3. Same positive exponent, larger base gives larger value since a^0.3 is increasing in a.",
    rubric: "比较指数式大小：底数相同比指数（正底数>1时递增），指数相同比底数（正指数时递增）。",
    conceptTags: ["functions", "exponentials"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "fn04", category: "functions",
    title: "对数函数定义域", titleEn: "Domain of a logarithmic function",
    content: "求函数 f(x)=log₃(x²-4) 的定义域。",
    contentEn: "Find the domain of f(x)=log₃(x²-4).",
    standardAnswer: "答案：x<-2 或 x>2，即 (-∞,-2)∪(2,+∞)。要求真数 x²-4>0，解得 x²>4，|x|>2。",
    standardAnswerEn: "Answer: x∈(-∞,-2)∪(2,+∞). Need x²-4>0 → |x|>2.",
    rubric: "对数的真数必须为正。解不等式 x²>4 时注意两端都考虑。",
    conceptTags: ["functions", "logarithms"], domain: "algebra", difficulty: "medium",
  },
  {
    id: "fn05", category: "functions",
    title: "函数的单调区间", titleEn: "Monotonic intervals of a function",
    content: "求函数 f(x)=x²-4x+3 的单调递减区间。",
    contentEn: "Find the decreasing interval of f(x)=x²-4x+3.",
    standardAnswer: "答案：(-∞, 2]。配方：f(x)=(x-2)²-1，顶点在 x=2。二次函数开口向上，在顶点左侧单调递减，故递减区间为 (-∞, 2]。",
    standardAnswerEn: "Answer: (-∞, 2]. Vertex at x=2 (from completing square); parabola opens upward, so decreasing for x≤2.",
    rubric: "二次函数 f(x)=a(x-h)²+k：a>0时对称轴 x=h 左边递减，右边递增。",
    conceptTags: ["functions", "quadratic"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "fn06", category: "functions",
    title: "周期函数", titleEn: "Period of a function",
    content: "已知 f(x+3)=f(x) 对所有 x 成立，且 f(1)=4，求 f(100)。",
    contentEn: "f is periodic with f(x+3)=f(x) for all x. Given f(1)=4, find f(100).",
    standardAnswer: "答案：4。周期为3，100=3×33+1，故 f(100)=f(1)=4。",
    standardAnswerEn: "Answer: 4. Period 3; 100=3×33+1, so f(100)=f(1)=4.",
    rubric: "周期函数：f(x+T)=f(x)，利用 100 mod 3=1 找同余位置。",
    conceptTags: ["functions"], domain: "algebra", difficulty: "easy",
  },
  {
    id: "fn07", category: "functions",
    title: "分段函数", titleEn: "Piecewise function",
    content: "设 f(x)=x+2（x<0）或 f(x)=x²（x≥0）。求 f(-3)+f(2)。",
    contentEn: "Let f(x)=x+2 for x<0, and f(x)=x² for x≥0. Find f(-3)+f(2).",
    standardAnswer: "答案：3。f(-3)=-3+2=-1（用第一段）；f(2)=4（用第二段）；f(-3)+f(2)=-1+4=3。",
    standardAnswerEn: "Answer: 3. f(-3)=-1 (first branch); f(2)=4 (second branch); sum=3.",
    rubric: "分段函数：根据 x 的范围选择对应的表达式代入计算。",
    conceptTags: ["functions"], domain: "algebra", difficulty: "easy",
  },

  // ── 容斥与鸽笼 ────────────────────────────────────────────────────────────────
  {
    id: "q03", category: "counting",
    title: "容斥原理基础", titleEn: "Inclusion-exclusion principle",
    content: "100 名学生中，60 人学法语，50 人学西班牙语，30 人两门都学。求只学一门语言的人数。",
    contentEn: "100 students: 60 study French, 50 Spanish, 30 study both. How many study exactly one language?",
    standardAnswer: "答案：50 人。|F∪S|=60+50-30=80；只学一门=80-30=50。（或：只学法语=60-30=30，只学西班牙=50-30=20，合计50）",
    standardAnswerEn: "Answer: 50. Only French: 30; only Spanish: 20; total exactly one: 50.",
    rubric: "容斥：|A∪B|=|A|+|B|-|A∩B|。只学一门=|A|+|B|-2|A∩B|=|A∪B|-|A∩B|。",
    conceptTags: ["counting", "inclusion_exclusion"], domain: "combinatorics", difficulty: "easy",
  },
  {
    id: "q06", category: "counting",
    title: "鸽巢原理", titleEn: "Pigeonhole principle",
    content: "抽屉里有红、蓝、绿袜子各10双（共30只），至少要取出几只，才能保证有两只同色的袜子？",
    contentEn: "A drawer has 10 red, 10 blue, 10 green socks (30 total). How many must you draw to guarantee a matching pair?",
    standardAnswer: "答案：4只。有3种颜色（3个抽屉），取3只可能每种各1只，无配对。取第4只必与某颜色相同，由鸽巢原理，4只中必有2只同色。",
    standardAnswerEn: "Answer: 4. With 3 colours, drawing 3 can give one of each. The 4th guarantees a match by pigeonhole.",
    rubric: "鸽巢原理：n+1个物品放入n个盒子，至少一个盒子有2个。颜色数=盒子数。",
    conceptTags: ["counting", "pigeonhole"], domain: "combinatorics", difficulty: "easy",
  },
  {
    id: "cnt01", category: "counting",
    title: "容斥：三集合", titleEn: "Inclusion-exclusion with three sets",
    content: "200人中：会说中文100人，英文80人，法文60人；会说中英两种40人，中法30人，英法20人，三种都会10人。求至少会一种语言的人数。",
    contentEn: "200 people: 100 Chinese, 80 English, 60 French, 40 Chinese+English, 30 Chinese+French, 20 English+French, 10 all three. Find those speaking at least one language.",
    standardAnswer: "答案：160人。|C∪E∪F|=100+80+60-40-30-20+10=160。",
    standardAnswerEn: "Answer: 160. |C∪E∪F|=100+80+60-40-30-20+10=160.",
    rubric: "三集合容斥：|A∪B∪C|=|A|+|B|+|C|-|A∩B|-|A∩C|-|B∩C|+|A∩B∩C|。",
    conceptTags: ["counting", "inclusion_exclusion"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "cnt02", category: "counting",
    title: "鸽巢：生日问题", titleEn: "Pigeonhole: birthday problem",
    content: "一年有365天，至少需要多少人，才能保证其中有两人生日相同？",
    contentEn: "A year has 365 days. How many people are needed to guarantee two share a birthday?",
    standardAnswer: "答案：366人。366人放入365个抽屉（天），由鸽巢原理必有两人共享一个生日。",
    standardAnswerEn: "Answer: 366. By pigeonhole (366 people, 365 days), at least two share a birthday.",
    rubric: "最坏情况：前365人可能各有不同生日，第366人必与某人重合。",
    conceptTags: ["counting", "pigeonhole"], domain: "combinatorics", difficulty: "easy",
  },
  {
    id: "cnt03", category: "counting",
    title: "错位排列", titleEn: "Derangements",
    content: "4封信随机放入4个信封，求没有一封放对的方案数。",
    contentEn: "4 letters are randomly placed into 4 envelopes. Find the number of derangements (no letter in its correct envelope).",
    standardAnswer: "答案：9。D₄=4!(1-1/1!+1/2!-1/3!+1/4!)=24(1/2-1/6+1/24)=24×(12-4+1)/24=9。",
    standardAnswerEn: "Answer: 9. D₄=4!(½-⅙+1/24)=9.",
    rubric: "错排公式 Dₙ=n!∑(-1)^k/k!（k=0到n）。D₄=9 是经典结果，可直接枚举验证。",
    conceptTags: ["counting", "inclusion_exclusion", "permutations"], domain: "combinatorics", difficulty: "hard",
  },
  {
    id: "cnt04", category: "counting",
    title: "整除计数", titleEn: "Counting divisible numbers",
    content: "1到200中，能被3整除但不能被5整除的正整数有多少个？",
    contentEn: "How many integers from 1 to 200 are divisible by 3 but not by 5?",
    standardAnswer: "答案：54。能被3整除：⌊200/3⌋=66；能被15整除（同时被3和5）：⌊200/15⌋=13。答：66-13=53。\n修正：⌊200/3⌋=66（198/3=66 ✓），⌊200/15⌋=13（195/15=13 ✓）。答案：66-13=53。",
    standardAnswerEn: "Answer: 53. Div by 3: ⌊200/3⌋=66; div by 15: ⌊200/15⌋=13; result: 66-13=53.",
    rubric: "被3但不被5整除=被3整除-被15整除。用容斥和取整函数。",
    conceptTags: ["counting", "inclusion_exclusion", "divisibility"], domain: "combinatorics", difficulty: "medium",
  },
  {
    id: "cnt05", category: "counting",
    title: "鸽巢：图论着色", titleEn: "Pigeonhole in graph coloring",
    content: "在6人聚会中，每两人要么是朋友要么是陌生人。证明：必存在3人两两都是朋友，或3人两两都是陌生人。",
    contentEn: "At a party of 6 people, any two are either friends or strangers. Prove there exist 3 mutual friends or 3 mutual strangers.",
    standardAnswer: "答案：取任意一人 A，其余5人中，对 A 来说有「朋友」或「陌生人」两类。由鸽巢原理，至少有3人同属一类（5人分2类，5÷2向上取整=3）。设有3人 B,C,D 都是 A 的朋友，则：若B,C,D中任意两人也是朋友，则与A构成3人互为朋友；否则B,C,D中存在陌生人对，设B与C是陌生人，则B,C,D不全朋友，继续找另一对……实际B,C中若有一对是陌生人（如B和C），则B和C已是陌生人，再由D与B或C的关系可找三人。完整证明：若B,C均为A的朋友：①若B与C是朋友→{A,B,C}三人互为朋友✓；②若B与C是陌生人→还需D的关系进一步分析，但最终可证。（标准6人拉姆齐定理证明，R(3,3)=6。）",
    standardAnswerEn: "Answer: By Ramsey theory (R(3,3)=6). Pick any person A; among 5 others, by pigeonhole, at least 3 are all friends or all strangers with A. Then consider pairs within that group.",
    rubric: "R(3,3)=6 的经典证明。两步鸽巢：第一次对5人分两类，第二次对3人中的对再判断。",
    conceptTags: ["counting", "pigeonhole", "graph_theory"], domain: "combinatorics", difficulty: "hard",
  },
  {
    id: "cnt06", category: "counting",
    title: "多重容斥", titleEn: "Inclusion-exclusion with multiples",
    content: "1到100中，能被2、3或5整除的正整数有多少个？",
    contentEn: "How many integers from 1 to 100 are divisible by 2, 3, or 5?",
    standardAnswer: "答案：74。|A₂|=50, |A₃|=33, |A₅|=20; |A₂∩A₃|=|A₆|=16, |A₂∩A₅|=|A₁₀|=10, |A₃∩A₅|=|A₁₅|=6; |A₂∩A₃∩A₅|=|A₃₀|=3。|A₂∪A₃∪A₅|=50+33+20-16-10-6+3=74。",
    standardAnswerEn: "Answer: 74. |A∪B∪C|=50+33+20-16-10-6+3=74.",
    rubric: "三集合容斥；各交集对应最小公倍数。⌊100/6⌋=16, ⌊100/10⌋=10, ⌊100/15⌋=6, ⌊100/30⌋=3。",
    conceptTags: ["counting", "inclusion_exclusion", "divisibility"], domain: "combinatorics", difficulty: "medium",
  },
];

